# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python All conda OS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-18.04']
        #os: ['windows-latest', 'ubuntu-18.04', 'macos-latest']

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        curl -LO https://repo.anaconda.com/miniconda/Miniconda3-py37_4.11.0-Linux-x86_64.sh
        mkdir miniconda
        bash Miniconda3-4.2.12-Linux-x86_64.sh -p ./miniconda -b
        rm Miniconda3-4.2.12-Linux-x86_64.sh
        echo "export PATH=./miniconda/bin:$PATH" >> /etc/bash.bashrc
        export PATH=./miniconda/bin:$PATH
        pip install . pyinstaller
        conda install numpy scipy

        #conda install --name foo numpy scipy pyinstaller
    - name: Run Pyinstaller 1
      if: matrix.os == 'windows-latest'
      run: |
        python -m pyinstaller -c --icon=./src/exe/tigerbet/ico.ico --add-data "./src/exe/tigerbet/onnxruntime_providers_shared.dll;onnxruntime/capi" -F ./src/exe/tigerbet/tigerbet.py
    - name: Run Pyinstaller  2
      if: matrix.os == 'ubuntu-18.04'
      run: |
        /usr/share/miniconda/envs/foo/bin/python -m pyinstaller -c --icon=./src/exe/tigerbet/ico.ico --add-data ./src/exe/tigerbet/libonnxruntime_providers_shared.so:onnxruntime/capi -F ./src/exe/tigerbet/tigerbet.py
    - name: Run Pyinstaller 3
      if: matrix.os == 'macos-latest'
      run: |
        python -m pyinstaller -c --icon=./src/exe/tigerbet/ico.ico --add-data ./src/exe/tigerbet/libonnxruntime_providers_shared.so:onnxruntime/capi -F ./src/exe/tigerbet/tigerbet.py
        
    - uses: actions/upload-artifact@v3
      with:
        name: tigerbet-${{ matrix.os }}
        path: dist/*
