# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.6
      uses: actions/setup-python@v3
      with:
        python-version: "3.6"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip        
        pip install pipenv
        pipenv install --site-packages https://github.com/htylab/tigerseg/archive/main.zip
        pipenv install pyinstaller
    - name: Run Pyinstaller
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run pyinstaller -c --icon=ico.ico -F ./src/exe/tigerbet/tigerbet.py
        
    - uses: actions/upload-artifact@v2
      with:
        name: tigerbet
        path: dist/*
